# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cfbde2e9f41df8c69b6f02f7019a09b4ccd282547da4bf482b6a458db729f5368f85a8b4d276d560d02eba1a5e11ef4946a2f63b80e30e33ca996079cfc8122

test:
  secret_key_base: 7c34cd7622bae6f9ddddb73c1239012af3191fa84ed14a0596053bf39131b1b11ecc262115281a2a68b1b65aa59a814b2adda4b7e877ee386f8cd5a7ef57f38e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
